// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaDVk9Lj-q8NtIL3_0oFrs2seGLRZC0ek',
    appId: '1:467252444840:web:f678b80a960b8db7de4c9d',
    messagingSenderId: '467252444840',
    projectId: 'auth1-d6bd4',
    authDomain: 'auth1-d6bd4.firebaseapp.com',
    storageBucket: 'auth1-d6bd4.firebasestorage.app',
    measurementId: 'G-NX43BPECSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfrjww6zySaIMKJStQDRYRsfw87jTaJBM',
    appId: '1:467252444840:android:584e07fca5a261ffde4c9d',
    messagingSenderId: '467252444840',
    projectId: 'auth1-d6bd4',
    storageBucket: 'auth1-d6bd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrROexo5gl2lIlIgjGrIONmuiqJeC28b0',
    appId: '1:467252444840:ios:f6ed5721abd58258de4c9d',
    messagingSenderId: '467252444840',
    projectId: 'auth1-d6bd4',
    storageBucket: 'auth1-d6bd4.firebasestorage.app',
    iosBundleId: 'com.example.authenticationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrROexo5gl2lIlIgjGrIONmuiqJeC28b0',
    appId: '1:467252444840:ios:f6ed5721abd58258de4c9d',
    messagingSenderId: '467252444840',
    projectId: 'auth1-d6bd4',
    storageBucket: 'auth1-d6bd4.firebasestorage.app',
    iosBundleId: 'com.example.authenticationTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaDVk9Lj-q8NtIL3_0oFrs2seGLRZC0ek',
    appId: '1:467252444840:web:a2fa644e4d8f0357de4c9d',
    messagingSenderId: '467252444840',
    projectId: 'auth1-d6bd4',
    authDomain: 'auth1-d6bd4.firebaseapp.com',
    storageBucket: 'auth1-d6bd4.firebasestorage.app',
    measurementId: 'G-EPSD2DEQW1',
  );
}
